services:
  db:
   image: mysql:8.0
   restart: always
   container_name: db
   ports:
    - 3306:3306
   environment:
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_DB: testdb

  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - 8080:80